if(EXISTS "/Users/mshindarev/Documents/ITMO/labwork2-M1RCLE/tests/number_tests[1]_tests.cmake")
  include("/Users/mshindarev/Documents/ITMO/labwork2-M1RCLE/tests/number_tests[1]_tests.cmake")
else()
  add_test(number_tests_NOT_BUILT number_tests_NOT_BUILT)
endif()
